# Generated by Django 5.0.4 on 2024-08-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='gallery',
        ),
        migrations.CreateModel(
            name='RestaurantGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_gallery/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='restau.restaurant')),
            ],
        ),
    ]
