# Generated by Django 5.0.4 on 2024-08-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0002_remove_reservation_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='bgphoto',
            field=models.ImageField(blank=True, null=True, upload_to='bgphoto/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
