# Generated by Django 5.0.4 on 2024-08-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0005_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
