# Generated by Django 5.0.4 on 2024-09-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0009_action_remove_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
